---
- hosts: aliyun
  vars:
    http_port: 80
    max_client: 200

  remote_user: root
  tasks:
  - name: ensure apache is latest version
    yum:  pkg=httpd state=latest
  - name: write apache config file
    template: src=/srv/httpd.j2 dest=/etc/httpd.conf
    notify:
    - restart apache
  - name: ensure apache is running
    service: name=httpd state=started

  handlers:
  - name: restart apache
    service:  name=httpd  state=restart
